In [29]:
def convert_units(conversion_type, value):
    """
    Converts units based on the conversion type.
    Parameters:
    conversion_type (str): Type of conversion selected by user.
    value (float): Numeric value to convert.
    Returns:
    float: Converted value.
    """

    if conversion_type == "1":
        return value * 3.28084  # meters to feet
    elif conversion_type == "2":
        return value / 3.28084  # feet to meters
    elif conversion_type == "3":
        return value * 2.20462  # kg to pounds
    elif conversion_type == "4":
        return value / 2.20462  # pounds to kg
    elif conversion_type == "5":
        return value * 0.264172  # liters to gallons
    elif conversion_type == "6":
        return value / 0.264172  # gallons to liters
    else:
        return None


def unit_converter():
    print("Select Conversion Type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    choice = input("Enter choice (1-6): ")

    try:
        value = float(input("Enter value to convert: "))
        result = convert_units(choice, value)

        if result is None:
            print("Invalid conversion type selected.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Error: Please enter a valid numeric value.")

unit_converter()

Select Conversion Type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter choice (1-6): 5
Enter value to convert: 33
Converted value: 8.717676


In [3]:
def calculate_sum(numbers):
    """
    Returns the sum of numbers in the list.
    Parameters:
    numbers (list): List of numeric values.
    Returns:
    float: Sum of numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Returns the average of numbers in the list.
    Parameters:
    numbers (list): List of numeric values.
    Returns:
    float: Average of numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Returns the maximum number in the list.
    Parameters:
    numbers (list): List of numeric values.
    Returns:
    float: Maximum value.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Returns the minimum number in the list.
    Parameters:
    numbers (list): List of numeric values.
    Returns:
    float: Minimum value.
    """
    return min(numbers)


def math_operations():
    print("\nSelect Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice (1-4): ")

    try:
        numbers = list(map(float, input("Enter numbers separated by space: ").split()))

        if len(numbers) == 0:
            print("Error: List cannot be empty.")
            return

        if choice == "1":
            print("Sum:", calculate_sum(numbers))
        elif choice == "2":
            print("Average:", calculate_average(numbers))
        elif choice == "3":
            print("Maximum:", find_maximum(numbers))
        elif choice == "4":
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numeric values.")



math_operations()


Select Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 3
Enter numbers separated by space: 1 2 4
Maximum: 4.0


In [4]:
def extract_every_other(lst):
    return lst[::2]

In [5]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

In [6]:
def reverse_list(lst):
    return lst[::-1]

In [7]:
def remove_first_last(lst):
    return lst[1:-1]

In [8]:
def get_first_n(lst, n):
    return lst[:n]

In [9]:
def get_last_n(lst, n):
    return lst[-n:]

In [10]:
def flatten(lst):
    """
    Flattens a nested list by one level.
    """
    result = []
    for sublist in lst:
        result.extend(sublist)
    return result

In [11]:
def access_nested_element(lst, indices):
    """
    Access element from nested list using list of indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

In [12]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

In [13]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

In [14]:
def find_max(lst):
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

In [15]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

In [16]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

In [17]:
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

In [18]:
import numpy as np
# 1. Empty 2x2 array
a1 = np.empty((2, 2))
print("Empty 2x2:\n", a1)

# 2. All ones 4x2
a2 = np.ones((4, 2))
print("\nOnes 4x2:\n", a2)

# 3. Full array
a3 = np.full((3, 3), 7)
print("\nFull 3x3 filled with 7:\n", a3)

# 4. Zeros like existing array
a4 = np.zeros_like(a2)
print("\nZeros like a2:\n", a4)

# 5. Ones like existing array
a5 = np.ones_like(a4)
print("\nOnes like a4:\n", a5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
a6 = np.array(new_list)
print("\nConverted list:", a6)

Empty 2x2:
 [[7.4809e-319 0.0000e+000]
 [0.0000e+000 0.0000e+000]]

Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full 3x3 filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like a2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like a4:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Converted list: [1 2 3 4]


In [19]:
# 1. Values from 10 to 49
arr1 = np.arange(10, 50)
print("\n10 to 49:\n", arr1)

# 2. 3x3 matrix from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", arr2)

# 3. Identity matrix
arr3 = np.eye(3)
print("\nIdentity Matrix:\n", arr3)

# 4. Random array size 30 and mean
arr4 = np.random.random(30)
print("\nMean:", arr4.mean())

# 5. 10x10 random matrix min and max
arr5 = np.random.random((10,10))
print("\nMin:", arr5.min())
print("Max:", arr5.max())

# 6. Zero array size 10, replace 5th element
arr6 = np.zeros(10)
arr6[4] = 1
print("\nModified array:", arr6)

# 7. Reverse array
arr7 = np.array([1,2,0,0,4,0])
print("\nReversed:", arr7[::-1])

# 8. 2D array with 1 border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("\nBorder array:\n", arr8)

# 9. 8x8 checkerboard
checker = np.zeros((8,8))
checker[::2,1::2] = 1
checker[1::2,::2] = 1
print("\nCheckerboard:\n", checker)


10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean: 0.43653194393964584

Min: 0.0039790977907874225
Max: 0.9999820699753463

Modified array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("\nAdd:", x + y)

# 2. Subtract
print("\nSubtract:", x - y)

# 3. Multiply by integer
print("\nMultiply x by 3:", x * 3)

# 4. Square elements
print("\nSquare x:", x**2)

# 5. Dot products
print("\nv·w:", np.dot(v,w))
print("x·v:", np.dot(x,v))
print("x·y:", np.dot(x,y))

# 6. Concatenate
print("\nConcatenate x & y (rows):\n", np.vstack((x,y)))
print("\nConcatenate v & w (columns):\n", np.column_stack((v,w)))

# 7. Concatenate x & v
try:
    print(np.vstack((x,v)))
except ValueError as e:
    print("\nError:", e)
    print("Reason: Dimensions does not match ")


Add: [[ 6  8]
 [10 13]]

Subtract: [[-4 -4]
 [-4 -3]]

Multiply x by 3: [[ 3  6]
 [ 9 15]]

Square x: [[ 1  4]
 [ 9 25]]

v·w: 219
x·v: [29 77]
x·y:
 [[19 22]
 [50 58]]

Concatenate x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w (columns):
 [[ 9 11]
 [10 12]]
[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [27]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1.
A_inv = np.linalg.inv(A)
print("\nA * A_inv:\n", np.dot(A, A_inv))

# 2.
AB = np.dot(A,B)
BA = np.dot(B,A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# 3.
print("\n(AB)^T:\n", AB.T)
print("B^T A^T:\n", np.dot(B.T, A.T))


A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [28]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nUsing inverse:", X)

# Direct solution
X2 = np.linalg.solve(A,B)
print("\nUsing solve function:", X2)


Solution using inverse: [ 2.  1. -2.]

Solution using solve(): [ 2.  1. -2.]


In [23]:
import time
size = 1_000_000

# Python list
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
print("List Addition Time:", time.time() - start)

# NumPy
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2
print("NumPy Addition Time:", time.time() - start)

List Addition Time: 0.07466387748718262
NumPy Addition Time: 0.011814355850219727


In [24]:
# Python
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
print("List Multiplication Time:", time.time() - start)

# NumPy
start = time.time()
result = arr1 * arr2
print("NumPy Multiplication Time:", time.time() - start)

List Multiplication Time: 0.07289242744445801
NumPy Multiplication Time: 0.010059118270874023


In [25]:
# Python
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
print("List Dot Time:", time.time() - start)

# Numpy
start = time.time()
dot = np.dot(arr1, arr2)
print("NumPy Dot Time:", time.time() - start)

List Dot Time: 0.06536388397216797
NumPy Dot Time: 0.0010797977447509766


In [26]:
size = 1000

# Python lists
A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()
C = [[sum(A[i][k]*B[k][j] for k in range(size))
      for j in range(size)] for i in range(size)]
print("List Matrix Multiplication Time:", time.time() - start)

# Numpy
A_np = np.ones((size,size))
B_np = np.ones((size,size))

start = time.time()
C_np = np.dot(A_np, B_np)
print("NumPy Matrix Multiplication Time:", time.time() - start)

List Matrix Multiplication Time: 83.66921329498291
NumPy Matrix Multiplication Time: 0.04632902145385742
